# Generated by Django 3.2.10 on 2022-11-27 13:50

from django.db import migrations, models
import django.db.models.deletion
import property_management_database.app.goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsStorageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to=property_management_database.app.goods.models.goods_storage_image_update)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to=property_management_database.app.goods.models.goods_image_update)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmdb_app_goods.goodsstoragemodel')),
            ],
        ),
    ]
