version: "3.8"


services:
  pmdb:
    image: x007007007/pmdb:${VERSION?Version not set}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYPI_INDEX: http://devpi.home.x007007007.info/root/pypi/+simple/
        PYPI_TRUSTED_HOST: devpi.home.x007007007.info

  pmdb-web:
    image: x007007007/pmdb-web:${VERSION?Version not set}
    build:
      context: ./frontend/
      dockerfile: Dockerfile