# Generated by Django 3.2.10 on 2021-12-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pmdb_rbac.rolegroupmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('auth_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('permission_set', models.ManyToManyField(related_name='role_set', to='pmdb_rbac.PermissionModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupBindUserWithRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmdb_rbac.rolemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupDimensionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmdb_rbac.usergroupdimensionmodel')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pmdb_rbac.usergroupmodel')),
                ('role_group_set', models.ManyToManyField(blank=True, to='pmdb_rbac.RoleGroupModel')),
                ('user_set', models.ManyToManyField(blank=True, related_name='usergroup_set', through='pmdb_rbac.UserGroupBindUserWithRoleModel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('mgr_sub_group', 'manage sub group'),),
            },
        ),
        migrations.AddField(
            model_name='usergroupbinduserwithrolemodel',
            name='user_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pmdb_rbac.usergroupmodel'),
        ),
        migrations.AddField(
            model_name='rolegroupmodel',
            name='role_set',
            field=models.ManyToManyField(to='pmdb_rbac.RoleModel'),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='pmdb_rbac.permissiontypemodel'),
        ),
    ]
