# Generated by Django 3.2.10 on 2021-12-12 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ui', 'ui'), ('api', 'api')], max_length=32)),
                ('rule', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('group_set', models.ManyToManyField(related_name='role_set', to='auth.Group')),
                ('permission_set', models.ManyToManyField(related_name='role_set', to='pmdb_rbac.PermissionModel')),
                ('user_set', models.ManyToManyField(related_name='role_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
