# Generated by Django 3.2.10 on 2021-12-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pmdb_rbac', '0002_loaddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('rule', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='permissionmodel',
            name='rule',
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='dj_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='perm_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmdb_rbac.permissionconfigmodel'),
        ),
    ]
