# Generated by Django 3.2.10 on 2021-12-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmdb_rbac', '0003_add_perm_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionmodel',
            old_name='dj_permission',
            new_name='dj_perm',
        ),
    ]
