# Generated by Django 3.2.10 on 2021-12-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pmdb_rbac', '0004_rename_dj_permission_permissionmodel_dj_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodel',
            name='auth_group',
        ),
        migrations.RemoveField(
            model_name='rolemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='rolegroupmodel',
            name='auth_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
