# Generated by Django 3.2.10 on 2021-12-15 16:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import property_management_database.app.rbac.models._base


class Migration(migrations.Migration):

    dependencies = [
        ('pmdb_rbac', '0005_auto_20211214_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroupDimensionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            bases=(property_management_database.app.rbac.models._base.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmdb_rbac.resourcegroupdimensionmodel')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pmdb_rbac.resourcegroupmodel')),
            ],
            options={
                'permissions': (('mgr_sub_resource_group', 'manage sub resource group'),),
            },
            bases=(property_management_database.app.rbac.models._base.NameMixin, models.Model),
        ),
    ]
