# Generated by Django 3.2.9 on 2021-12-04 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistoryCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceHistoryPaymentTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=128)),
                ('number', models.FloatField()),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='pmdb_payment_alipay.balancehistorypaymenttypemodel')),
                ('pmdb_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmdb_payment_alipay.balancehistorycategorymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
