# Generated by Django 4.1.5 on 2023-01-25 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pmdb_app_hub", "0002_hubmodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="huboverviewmodel",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
